### PR TITLE
XPU: avoid COW materialization in linalg::lu_solve

### LINKED ISSUE #2919: [release/2.14] [XPU][upstream_ut][COW] Fix materialization in remaining TestCompositeComplianceXPU tests
### 🐛 Describe the bug

Split from: #2248

This issue tracks COW-related materialization failures on XPU backend.

## Affected tests (materialization-related)

- TestCompositeComplianceXPU.test_cow_input___rmatmul___xpu_float32
- TestCompositeComplianceXPU.test_cow_input_addbmm_xpu_float32
- TestCompositeComplianceXPU.test_cow_input_addmm_decomposed_xpu_float32
- TestCompositeComplianceXPU.test_cow_input_addmm_xpu_float32
- TestCompositeComplianceXPU.test_cow_input_addmv_xpu_float32
- TestCompositeComplianceXPU.test_cow_input_addr_xpu_float32
- TestCompositeComplianceXPU.test_cow_input_baddbmm_xpu_float32
- TestCompositeComplianceXPU.test_cow_input_bmm_xpu_float32
- TestCompositeComplianceXPU.test_cow_input_cdist_xpu_float32
- TestCompositeComplianceXPU.test_cow_input_cholesky_inverse_xpu_float32
- TestCompositeComplianceXPU.test_cow_input_cholesky_solve_xpu_float32
- TestCompositeComplianceXPU.test_cow_input_cholesky_xpu_float32
- TestCompositeComplianceXPU.test_cow_input_einsum_xpu_float32
- TestCompositeComplianceXPU.test_cow_input_linalg_cholesky_ex_xpu_float32
- TestCompositeComplianceXPU.test_cow_input_linalg_cholesky_xpu_float32
- TestCompositeComplianceXPU.test_cow_input_linalg_householder_product_xpu_float32
- TestCompositeComplianceXPU.test_cow_input_linalg_inv_ex_xpu_float32
- TestCompositeComplianceXPU.test_cow_input_linalg_inv_xpu_float32
- TestCompositeComplianceXPU.test_cow_input_linalg_lstsq_grad_oriented_xpu_float32
- TestCompositeComplianceXPU.test_cow_input_linalg_lstsq_xpu_float32
- TestCompositeComplianceXPU.test_cow_input_linalg_lu_factor_ex_xpu_float32
- TestCompositeComplianceXPU.test_cow_input_linalg_lu_factor_xpu_float32
- TestCompositeComplianceXPU.test_cow_input_linalg_lu_solve_xpu_float32
- TestCompositeComplianceXPU.test_cow_input_linalg_lu_xpu_float32
- TestCompositeComplianceXPU.test_cow_input_linalg_matrix_power_xpu_float32
- TestCompositeComplianceXPU.test_cow_input_linalg_multi_dot_xpu_float32
- TestCompositeComplianceXPU.test_cow_input_linalg_pinv_hermitian_xpu_float32
- TestCompositeComplianceXPU.test_cow_input_linalg_pinv_singular_xpu_float32
- TestCompositeComplianceXPU.test_cow_input_linalg_pinv_xpu_float32
- TestCompositeComplianceXPU.test_cow_input_linalg_qr_xpu_float32
- TestCompositeComplianceXPU.test_cow_input_linalg_svd_xpu_float32
- TestCompositeComplianceXPU.test_cow_input_linalg_tensorinv_xpu_float32
- TestCompositeComplianceXPU.test_cow_input_lu_solve_xpu_float32
- TestCompositeComplianceXPU.test_cow_input_lu_xpu_float32
- TestCompositeComplianceXPU.test_cow_input_matmul_xpu_float32
- TestCompositeComplianceXPU.test_cow_input_mm_xpu_float32
- TestCompositeComplianceXPU.test_cow_input_mv_xpu_float32
- TestCompositeComplianceXPU.test_cow_input_nn_functional_bilinear_xpu_float32
- TestCompositeComplianceXPU.test_cow_input_nn_functional_conv1d_xpu_float32
- TestCompositeComplianceXPU.test_cow_input_nn_functional_conv2d_xpu_float32
- TestCompositeComplianceXPU.test_cow_input_nn_functional_conv3d_xpu_float32
- TestCompositeComplianceXPU.test_cow_input_nn_functional_conv_transpose1d_xpu_float32
- TestCompositeComplianceXPU.test_cow_input_nn_functional_conv_transpose2d_xpu_float32
- TestCompositeComplianceXPU.test_cow_input_nn_functional_conv_transpose3d_xpu_float32
- TestCompositeComplianceXPU.test_cow_input_nn_functional_cross_entropy_xpu_float32
- TestCompositeComplianceXPU.test_cow_input_nn_functional_linear_xpu_float32
- TestCompositeComplianceXPU.test_cow_input_nn_functional_multi_head_attention_forward_xpu_float32
- TestCompositeComplianceXPU.test_cow_input_nn_functional_scaled_dot_product_attention_xpu_float32
- TestCompositeComplianceXPU.test_cow_input_ormqr_xpu_float32
- TestCompositeComplianceXPU.test_cow_input_pca_lowrank_xpu_float32
- TestCompositeComplianceXPU.test_cow_input_pinverse_xpu_float32
- TestCompositeComplianceXPU.test_cow_input_qr_xpu_float32
- TestCompositeComplianceXPU.test_cow_input_svd_lowrank_xpu_float32
- TestCompositeComplianceXPU.test_cow_input_svd_xpu_float32
- TestCompositeComplianceXPU.test_cow_input_tensordot_xpu_float32
- TestCompositeComplianceXPU.test_cow_input_topk_xpu_float32

## Problem

These failures are caused by unintended tensor materialization
triggered by mutable pointer access and incorrect RO/RW semantics.

## Goal

- eliminate unintended materialization
- enforce correct RO vs RW semantics
- pass COW compliance tests without skipping

## Previous attempts

Initial fixes and investigation were done in:

- https://github.com/pytorch/pytorch/pull/174374
- https://github.com/intel/torch-xpu-ops/pull/2857
- https://github.com/intel/torch-xpu-ops/pull/2865

These PRs introduced RO/RW wrapper adjustments and reduced
unintended materialization in several kernels.

However, a complete solution depends on proper constant pointer
support in oneDNN.

### Versions

Resolution of remaining materialization issues depends on oneDNN providing
an interface that supports constant (read-only) pointers.

The SH team has already submitted a JIRA to oneDNN regarding this.

We are currently waiting for oneDNN to introduce a const-pointer–aware
API (or provide an official recommendation), after which we can revisit
and finalize the COW cleanup on XPU.

### PR DESCRIPTION
**Pull request by gplutop7**
Fixes: https://github.com/intel/torch-xpu-ops/issues/2919

Use const_data_ptr for the LU input in XPU lu_solve to avoid unintended COW materialization.
This PR fixes: TestCompositeComplianceXPU.test_cow_input_linalg_lu_solve_xpu_float32

Note:
For this test to fully pass, COW fixes in XPU matmul paths are also required
(see https://github.com/pytorch/pytorch/pull/178305).

### CODE REVIEW

File: src/ATen/native/xpu/mkl/BatchLinearAlgebra.cpp [hunk 1]
```diff
@@ -241,7 +241,8 @@ static void apply_lu_solve_xpu_(
   int64_t ldb = b_.size(-2);
   int64_t stride_b = native::matrixStride(b_);
 
-  scalar_t* a = reinterpret_cast<scalar_t*>(lu_.data_ptr());
+  const auto* a_ro = static_cast<const scalar_t*>(lu_.const_data_ptr());
+  auto* a = const_cast<scalar_t*>(a_ro);
```
[the remark this answers is not in the document]
Comment (gplutop7) [reply src/ATen/native/xpu/mkl/BatchLinearAlgebra.cpp]: fixed

File: src/ATen/native/xpu/mkl/BatchLinearAlgebra.cpp [hunk 2]
```diff
@@ -129,7 +129,7 @@ void mkl_getrs(
       trans,
       n,
       nrhs,
-      a,
+      const_cast<scalar_t*>(a),
```
Comment (BBBela) [inline src/ATen/native/xpu/mkl/BatchLinearAlgebra.cpp]: Is this `const_cast()` really needed?
I did success to rebuild this code without the `const_cast()` here. From what I found the `getrs_batch()` function already accepts the const `a` parameter and the `const_cast()` is not needed.
Could you please verify if that is necessary or let me know why it is necessary? Because I may be missing something.

File: src/ATen/native/xpu/mkl/BatchLinearAlgebra.cpp [hunk 3]
```diff
@@ -241,7 +241,7 @@ static void apply_lu_solve_xpu_(
   int64_t ldb = b_.size(-2);
   int64_t stride_b = native::matrixStride(b_);
 
-  scalar_t* a = reinterpret_cast<scalar_t*>(lu_.data_ptr());
+  const auto* a = static_cast<const scalar_t*>(lu_.const_data_ptr());
```
Comment (BBBela) [inline src/ATen/native/xpu/mkl/BatchLinearAlgebra.cpp:244]:
```suggestion
  const scalar_t* a = static_cast<const scalar_t*>(lu_.const_data_ptr());
```
I would personally leave the `scalar_t` instead of `auto`, but that is not required and just my personal preference. So feel free to ignore it and resolve this comment.

File: src/ATen/native/xpu/mkl/BatchLinearAlgebra.cpp (hunk 2 above)
Comment (gplutop7) [reply src/ATen/native/xpu/mkl/BatchLinearAlgebra.cpp]: You’re right - I missed that getrs_batch already takes const inputs. The const_cast was unnecessary, and I removed it.

**Review by BBBela — APPROVED** [review]
Looks good to me, thanks!
But the current changes locally makes the linter to fail. At least for me. Please check it and verify if the linter job fails.
I checked with:
```bash
lintrunner init
lintrunner -m origin/main
lintrunner f -m origin/main
```

**Review by CuiYifeng — APPROVED** [review]
LGTM. Please retrigger CI.

**Comment by chuanqi129** [comment]
✅ PR has been successfully merged by @gplutop7.
