### PR TITLE
Ensure tensors are contiguous for batch normalization kernels

### LINKED ISSUE #2233: RuntimeError: out_invstd.dim() == 1 && out_invstd.is_contiguous() && out_invstd.sizes()[0]
### 🐛 Describe the bug

- [ ] PYTORCH_OPINFO_SAMPLE_INPUT_INDEX=0 PYTORCH_TEST_WITH_SLOW=1 python test/test_ops.py TestCommonXPU.test_out__native_batch_norm_legit_xpu_float32
- [ ] test_out_native_batch_norm_xpu_float32

```
______________________________________________________________________ TestCommonXPU.test_out__native_batch_norm_legit_xpu_float32 _______________________________________________________________________
Traceback (most recent call last):                                                                                                                                                                        
  File "/home/daisyden/miniforge3/envs/torch_ops_s2/lib/python3.10/site-packages/torch/testing/_internal/common_device_type.py", line 1151, in test_wrapper                                               
    return test(*args, **kwargs)                                                                                                                                                                          
  File "/home/daisyden/upstream/torch_ops_s2/test/test_ops.py", line 1166, in test_out                                                                                                                    
    _compare_out(_case_one_transform)                                                                                                                                                                     
  File "/home/daisyden/upstream/torch_ops_s2/test/test_ops.py", line 1131, in _compare_out                                                                                                                
    op_out(out=out)                                                                                                                                                                                       
  File "/home/daisyden/miniforge3/envs/torch_ops_s2/lib/python3.10/site-packages/torch/testing/_internal/opinfo/core.py", line 1186, in __call__                                                          
    return self.op(*args, **kwargs)                                                                                                                                                                       
RuntimeError: out_invstd.dim() == 1 && out_invstd.is_contiguous() && out_invstd.sizes()[0] INTERNAL ASSERT FAILED at "/home/daisyden/upstream/torch_ops_s2/third_party/torch-xpu-ops/src/ATen/native/xpu/s
ycl/BatchNormKernels.cpp":584, please report a bug to PyTorch.                                                                                                                                            
                                                                                                                                                                                                          
The above exception was the direct cause of the following exception:                                                                                                                                      
                                                                                                                                                                                                          
Traceback (most recent call last):                                                                                                                                                                        
  File "/home/daisyden/miniforge3/envs/torch_ops_s2/lib/python3.10/site-packages/torch/testing/_internal/common_utils.py", line 3300, in wrapper                                                          
    method(*args, **kwargs)                                                                                                                                                                               
  File "/home/daisyden/miniforge3/envs/torch_ops_s2/lib/python3.10/site-packages/torch/testing/_internal/common_device_type.py", line 428, in instantiated_test                                           
    result = test(self, **param_kwargs)                                                                                                                                                                   
  File "/home/daisyden/miniforge3/envs/torch_ops_s2/lib/python3.10/site-packages/torch/testing/_internal/common_utils.py", line 1707, in wrapper
    fn(*args, **kwargs)
  File "/home/daisyden/miniforge3/envs/torch_ops_s2/lib/python3.10/site-packages/torch/testing/_internal/common_device_type.py", line 1163, in test_wrapper
    raise e_tracked from e
Exception: out_invstd.dim() == 1 && out_invstd.is_contiguous() && out_invstd.sizes()[0] INTERNAL ASSERT FAILED at "/home/daisyden/upstream/torch_ops_s2/third_party/torch-xpu-ops/src/ATen/native/xpu/sycl
/BatchNormKernels.cpp":584, please report a bug to PyTorch. 

Caused by sample input at index 0: SampleInput(input=Tensor[size=(5, 5, 5), device="xpu:0", dtype=torch.float32], args=(Tensor[size=(5,), device="xpu:0", dtype=torch.float32],Tensor[size=(5,), device="x
pu:0", dtype=torch.float32],Tensor[size=(5,), device="xpu:0", dtype=torch.float32],Tensor[size=(5,), device="xpu:0", dtype=torch.float32],True,0.5,0.6), kwargs={}, broadcasts_input=False, name='')

```

### Versions

Branch: https://github.com/daisyden/pytorch/daisyden/torch_ops_s2

Collecting environment information...
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.5 LTS (x86_64)
GCC version: (Ubuntu 13.1.0-8ubuntu1~22.04) 13.1.0
Clang version: Could not collect
CMake version: version 3.31.6
Libc version: glibc-2.35

Python version: 3.10.19 | packaged by conda-forge | (main, Oct 22 2025, 22:29:10) [GCC 14.3.0] (64-bit runtime)
Python platform: Linux-5.15.0-73-generic-x86_64-with-glibc2.35
Is CUDA available: N/A
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect
Is XPU available: N/A
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: N/A

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   46 bits physical, 57 bits virtual
Byte Order:                      Little Endian
CPU(s):                          48
On-line CPU(s) list:             0-47
Vendor ID:                       GenuineIntel
Model name:                      Intel(R) Xeon(R) Gold 6342 CPU @ 2.80GHz
CPU family:                      6
Model:                           106
Thread(s) per core:              2
Core(s) per socket:              24
Socket(s):                       1
Stepping:                        6
CPU max MHz:                     3500.0000
CPU min MHz:                     800.0000
BogoMIPS:                        5600.00
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 invpcid_single intel_ppin ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb intel_pt avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local split_lock_detect wbnoinvd dtherm ida arat pln pts hwp hwp_act_window hwp_epp hwp_pkg_req avx512vbmi umip pku ospke avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg tme avx512_vpopcntdq la57 rdpid fsrm md_clear pconfig flush_l1d arch_capabilities
Virtualization:                  VT-x
L1d cache:                       1.1 MiB (24 instances)
L1i cache:                       768 KiB (24 instances)
L2 cache:                        30 MiB (24 instances)
L3 cache:                        36 MiB (1 instance)
NUMA node(s):                    1
NUMA node0 CPU(s):               0-47
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Mitigation; Clear CPU buffers; SMT vulnerable
Vulnerability Retbleed:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Enhanced IBRS, IBPB conditional, RSB filling, PBRSB-eIBRS SW sequence
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected

Versions of relevant libraries:
[pip3] mypy==1.16.0
[pip3] mypy_extensions==1.1.0
[pip3] numpy==1.22.4
[pip3] onnx==1.19.1
[pip3] onnx-ir==0.1.12
[pip3] onnxscript==0.5.4
[pip3] optree==0.13.0
[pip3] torch==2.10.0a0+gite221c63
[conda] numpy                     1.22.4                   pypi_0    pypi
[conda] optree                    0.13.0                   pypi_0    pypi
[conda] torch                     2.10.0a0+gite221c63          pypi_0    pypi

### PR DESCRIPTION
**Pull request by tszulist-hbn**
This PR fixes #2233 in the XPU batch normalization kernel batch_norm_mean_var. The Impl::Contiguous code path unconditionally called batch_norm_stats_template, which assumes contiguous output tensors (save_mean, save_var). When non-contiguous output tensors were passed, this could lead to incorrect results.

### What this PR does:

Adds contiguity checks on the save_mean and save_var output tensors in the Impl::Contiguous case of batch_norm_mean_var.
If either output tensor is non-contiguous, falls through to Impl::General, which uses var_mean_out and correctly handles non-contiguous outputs.
Adds regression tests covering the Impl::Contiguous path for BatchNorm1d/2d/3d across float32, float16, and bfloat16, as well as a test for non-contiguous running stats.
### Why this is needed:

PyTorch operators are expected to work transparently with non-contiguous tensors.
Aligns the Impl::Contiguous path with the Impl::ChannelsLast path, which already had this guard.
### Scope / Impact:

Affects only batch_norm_mean_var in the XPU backend.
No API changes.
Behavior is unchanged for already-contiguous output tensors.
### Validation:

New regression tests in test/regressions/test_batch_norm.py validate correctness against CPU reference for contiguous inputs and non-contiguous running stats.
No regressions observed in BatchNorm-related test coverage.

### CODE REVIEW

File: src/ATen/native/xpu/sycl/BatchNormKernels.cpp [hunk 1]
```diff
@@ -3832,12 +3832,16 @@ void batch_norm_mean_var(
...
+      if ((!save_mean.defined() || save_mean.is_contiguous()) &&
+          (!save_var.defined() || save_var.is_contiguous())) {
+        AT_DISPATCH_FLOATING_TYPES_AND2(
+            kHalf, kBFloat16, self.scalar_type(), "batch_norm_stats_xpu", [&] {
+              batch_norm_stats_template<scalar_t, int32_t, Var>(
+                  save_mean, save_var, self, dummy_epsilon);
+            });
+        return;
+      }
+      [[fallthrough]];
```
Comment (astachowiczhabana) [inline src/ATen/native/xpu/sycl/BatchNormKernels.cpp:3844]: I'm worried here that non-contiguous case we fall-through the next and go to the general case which would use var_mean_out. That could potentially mean slower perf. The alternative approach is to create copy of original kernel (just like we do in max_pool2d_with_indices_out_xpu). This is a choice between memory vs (potential) performance hit. @EikanWang what do you think?

**Comment by tszulist-hbn** [comment]
@guangyey, thank you for your suggestion. Note, in the meantime, I have pushed yet another update, with a little deduplication refactor. Could you check this once more? Aren't the explicit fast paths redundant — `dispatch_with_contig_handling` already passes `save_mean`/`save_var` directly through when they're contiguous (no allocations, no copies).

**Review by guangyey — COMMENTED** [review]
The code change looks good to me. However, the regression test seems useless.
Because they could pass on nightly build without this PR fixed.
```bash
platform linux -- Python 3.10.20, pytest-9.0.2, pluggy-1.6.0 -- /home/sdp/miniforge3/envs/guangyey_nightly/bin/python3.10
cachedir: .pytest_cache
hypothesis profile 'default'
rootdir: /home/sdp/guangyey
plugins: hypothesis-6.151.9
collected 12 items                                                                                                                                                                                                     

test.py::TestBatchNormContiguous::test_bn1d_3d_contiguous_bfloat16 PASSED
test.py::TestBatchNormContiguous::test_bn1d_3d_contiguous_float16 PASSED
test.py::TestBatchNormContiguous::test_bn1d_3d_contiguous_float32 PASSED
test.py::TestBatchNormContiguous::test_bn2d_contiguous_bfloat16 PASSED
test.py::TestBatchNormContiguous::test_bn2d_contiguous_float16 PASSED
test.py::TestBatchNormContiguous::test_bn2d_contiguous_float32 PASSED
test.py::TestBatchNormContiguous::test_bn2d_contiguous_mixed_weight_bias PASSED
test.py::TestBatchNormContiguous::test_bn2d_contiguous_running_stats PASSED
test.py::TestBatchNormContiguous::test_bn2d_noncontiguous_running_stats_update PASSED
test.py::TestBatchNormContiguous::test_bn3d_contiguous_bfloat16 PASSED
test.py::TestBatchNormContiguous::test_bn3d_contiguous_float16 PASSED
test.py::TestBatchNormContiguous::test_bn3d_contiguous_float32 PASSED

================================================================================================== 12 passed in 3.62s ==================================================================================================
```
image

**Review by guangyey — COMMENTED** [review]
Please add a validated regression test.
